sudo: required

stage_generic_linux: &stage_generic_linux
  os: linux
  # change dir
  before_script:
    - mkdir qutip_testing
    - cd qutip_testing
  # command to run tests
  script: 
    - python -m qutip.about
    - nosetests --verbosity=2 --with-coverage --cover-package=qutip qutip
  install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
    - source activate test-environment
    - conda install mkl blas=*=mkl numpy scipy nose cython coveralls
    - python setup.py install

stage_linux_35: &stage_linux_35
  <<: *stage_generic_linux
  dist: trusty
  language: python
  python: 3.5

stage_linux_36: &stage_linux_36
  <<: *stage_generic_linux
  dist: trusty
  language: python
  python: 3.6

stage_linux_37: &stage_linux_37
  <<: *stage_generic_linux
  dist: xenial
  language: python
  python: 3.7

stage_linux_37_openblas: &stage_linux_37_openblas
  <<: *stage_generic_linux
  dist: xenial
  install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
    - source activate test-environment
    - conda install nomkl blas=*=openblas numpy scipy nose cython
    - python setup.py install

stage_linux_37_omp: &stage_linux_37_omp
  <<: *stage_generic_linux
  dist: xenial
  install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
    - source activate test-environment
    - conda install mkl blas=*=mkl numpy scipy nose cython coveralls
    - python setup.py install --with-openmp
  after_success:
    - coveralls

stage_osx: &stage_osx
  os: osx
  osx_image: xcode10
  language: generic
  # change dir
  before_script:
    - mkdir qutip_testing
    - cd qutip_testing
  # command to run tests
  script: 
    - python -m qutip.about
    - nosetests --verbosity=2 --with-coverage --cover-package=qutip qutip
  install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
    - source activate test-environment
    - conda install mkl blas=*=mkl numpy scipy nose cython coveralls
    - python setup.py install

stages:
  - linux
  - osx

jobs:
  include:
    - stage: linux
      <<: *stage_linux_35
    - stage: linux
      <<: *stage_linux_36
    - stage: linux
      <<: *stage_linux_37
    - stage: linux
      <<: *stage_linux_37_omp
    - stage: linux
      <<: *stage_linux_37_openblas
    - stage: osx
      <<: *stage_osx